# Generated by Django 4.1.5 on 2023-05-05 13:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import main.my_validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BioVelesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio_veles', models.TextField(default='Veles Bio', max_length=1500)),
                ('foto_veles', models.ImageField(default='.', upload_to='veles')),
            ],
        ),
        migrations.CreateModel(
            name='ComposerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=80)),
                ('years', models.CharField(blank=True, max_length=11, null=True, validators=[main.my_validators.life_years_validator])),
            ],
        ),
        migrations.CreateModel(
            name='CyclePartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LinksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='YouTube', max_length=12)),
                ('link', models.URLField(default='.')),
                ('icon', models.ImageField(default='image', upload_to='icons')),
            ],
        ),
        migrations.CreateModel(
            name='MediaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(default='.', upload_to='veles')),
            ],
        ),
        migrations.CreateModel(
            name='OperaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=500)),
                ('opus', models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator('[Oo]p\\.\\s?\\d{1,3}')])),
                ('composer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operas', to='main.composermodel')),
            ],
        ),
        migrations.CreateModel(
            name='VelesComponentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('instrument', models.CharField(default='guitar', max_length=50)),
                ('bio', models.TextField(max_length='2000')),
                ('picture', models.ImageField(default='', upload_to='veles_components')),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='VideosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.URLField(default='')),
                ('title', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SongModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.CharField(max_length=200)),
                ('cycle_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='main.cyclepartmodel')),
                ('opera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='op_songs', to='main.operamodel')),
            ],
        ),
        migrations.AddField(
            model_name='cyclepartmodel',
            name='opera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='main.operamodel'),
        ),
    ]
